// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/exhibit/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exhibit/[id].get').default>>>>
    }
    '/api/exhibit/all': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exhibit/all.get').default>>>>
    }
    '/api/exhibit/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exhibit/create.post').default>>>>
    }
    '/api/exhibit/favorite/:id': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exhibit/favorite/[id].post').default>>>>
    }
    '/api/exhibit/favorite/:id/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exhibit/favorite/[id]/status.get').default>>>>
    }
    '/api/exhibit/most-liked': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exhibit/most-liked.get').default>>>>
    }
    '/api/exhibit/period/:periodId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exhibit/period/[periodId].get').default>>>>
    }
    '/api/exhibit/period/:userId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exhibit/period/[userId].get').default>>>>
    }
    '/api/exhibit/recommended': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exhibit/recommended.get').default>>>>
    }
    '/api/exhibit/update': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exhibit/update.put').default>>>>
    }
    '/api/exhibit/upload-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exhibit/upload-image.post').default>>>>
    }
    '/api/images': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images.get').default>>>>
    }
    '/api/timeline-events': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/timeline-events').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.17.4_@parcel+watcher_6401d01ba2ca8f9f2da57d5e24aedf28/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}