// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.4_@parcel+watcher_6401d01ba2ca8f9f2da57d5e24aedf28/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.4_@parcel+watcher_6401d01ba2ca8f9f2da57d5e24aedf28/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.4_@parcel+watcher_6401d01ba2ca8f9f2da57d5e24aedf28/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+supabase@1.5.1/node_modules/@nuxtjs/supabase/dist/runtime/plugins/supabase.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+supabase@1.5.1/node_modules/@nuxtjs/supabase/dist/runtime/plugins/supabase.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.4_@parcel+watcher_6401d01ba2ca8f9f2da57d5e24aedf28/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.4_@parcel+watcher_6401d01ba2ca8f9f2da57d5e24aedf28/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.4_@parcel+watcher_6401d01ba2ca8f9f2da57d5e24aedf28/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.4_@parcel+watcher_6401d01ba2ca8f9f2da57d5e24aedf28/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.4_@parcel+watcher_6401d01ba2ca8f9f2da57d5e24aedf28/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@9.5.4_@vue+com_44fe13fbc3f5489d1ecc633bba5853b3/node_modules/@nuxtjs/i18n/dist/runtime/plugins/switch-locale-path-ssr.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@9.5.4_@vue+com_44fe13fbc3f5489d1ecc633bba5853b3/node_modules/@nuxtjs/i18n/dist/runtime/plugins/route-locale-detect.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@9.5.4_@vue+com_44fe13fbc3f5489d1ecc633bba5853b3/node_modules/@nuxtjs/i18n/dist/runtime/plugins/i18n.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.4_@parcel+watcher_6401d01ba2ca8f9f2da57d5e24aedf28/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.4_@parcel+watcher_6401d01ba2ca8f9f2da57d5e24aedf28/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@2.4.1_vite@6_57633b9e6f141b941f587ab2ab2e1e96/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@2.4.1_vite@6_57633b9e6f141b941f587ab2ab2e1e96/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+supabase@1.5.1/node_modules/@nuxtjs/supabase/dist/runtime/plugins/auth-redirect.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.4_@parcel+watcher_6401d01ba2ca8f9f2da57d5e24aedf28/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.4_@parcel+watcher_6401d01ba2ca8f9f2da57d5e24aedf28/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../plugins/auth.js")> &
  InjectionType<typeof import("../../plugins/fontawesome.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@9.5.4_@vue+com_44fe13fbc3f5489d1ecc633bba5853b3/node_modules/@nuxtjs/i18n/dist/runtime/plugins/ssg-detect.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'supabase' | 'supabase' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'i18n:plugin:switch-locale-path-ssr' | 'i18n:plugin:route-locale-detect' | 'i18n:plugin' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'auth-redirect' | 'nuxt:checkIfLayoutUsed' | 'i18n:plugin:ssg-detect'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
